#!/bin/bash
# Test dirvish connection

#VAULT="" # No trailing /
#CONF="$VAULT/dirvish/default.conf"

function usage {
    echo "Usage: $0 /path/to/vault"
    echo "Where the path is excluding any trailing /-characters."
}

## -------------------------------------------------------------------------- ##
# Colors for prettier print
U='\033[0;0m'
R='\033[0;31m'
Y='\033[1;33m'
G='\033[0;32m'
B='\033[0;34m'
## -------------------------------------------------------------------------- ##
## Sanity checks
if [ $# -ne 1 ]; then
    echo -e "${R}Error:${U} Expected one vault directory as input." 1>&2
    usage 1>&2
    exit 8
else
    VAULT="$1"
    CONF="$VAULT/dirvish/default.conf"
fi
if [ ! -f "$CONF" ] ; then
    echo -e "${R}Error:${U} Directory $VAULT is not a Dirvish vault." 1>&2
    usage 1>&2
    exit 8
fi

## -------------------------------------------------------------------------- ##
## Do the needful

CLIENT="$(grep -E '^client:' "$CONF" | cut -f 2 -d ' ')"
PORT="$(grep -E '^rsh:' "$CONF" | grep -oE -- '-p [0-9]{2,5}' | cut -f 2 -d ' ')" # Asssumption: Remote shell only exist to change port for dirvish

# echo "Vault : $VAULT"
# echo "Conf  : $CONF"
# echo "Client: $CLIENT"
# echo "PORT  : $PORT"
# exit # Safety Exit

if [ -z "$PORT" ] ;then
    PORT=22
fi

if [ $UID -ne 0 ] ; then
    echo -e "${Y}Warning:${U} Not running as root as Dirvish probably does." 1>&2
    usage 1>&2
fi

if ! $(ping -c 1 -W 5 $CLIENT > /dev/null); then
    echo -e "${R}Fail:${U} Failure to ping $CLIENT"
    exit 1
fi
if ! $(ssh $CLIENT -p $PORT -o 'BatchMode yes' -o 'ConnectTimeout 5' exit); then
    echo -e "${R}Fail:${U} Couldn't connect to $CLIENT on port $PORT as $(whoami)"
    exit 1
fi

echo -e "${G}Success:${U} Ping and connection test successful."

exit 0
