#!/bin/bash

function synopsis {
    echo "Print the paths to different versions of a given file within a vault."
}
function usage {
    echo "Usage: $0 path/to/vault /full/path/to/file"
    echo "Where the paths are excluding any trailing /-characters."
    echo "The file path is a full path as defined on the backed up machine."

}
function warn {
    echo -e "$Y Warning:$U $1" 1>&2
}
## -------------------------------------------------------------------------- ##
# Colors for prettier print
U='\033[0;0m'
R='\033[0;31m'
Y='\033[1;33m'
G='\033[0;32m'
B='\033[0;34m'
## -------------------------------------------------------------------------- ##
## Sanity checks
if [ $# -ne 2 ]; then
    echo -e "${R}Error:${U} Expected one vault directory and one file as input." 1>&2
    usage 1>&2
    exit 8
else
    VAULT="$1"
    FILE="$2" # Full path
fi
if [ ! -f "$VAULT/dirvish/default.conf" ] ; then
    echo -e "${R}Error:${U} Directory $VAULT is not a Dirvish vault." 1>&2
    usage 1>&2
    exit 8
fi

if [ $UID -ne 0 ] ; then
    warn "This script will probably work better if run as root."
    usage 1>&2
    exit 8
fi

## -------------------------------------------------------------------------- ##
TREE="tree"
## -------------------------------------------------------------------------- ##


curr_checksum="dummy init value"
for d in $(ls $VAULT | grep -E '[0-9]{8}') ; do
    # Reminder: FILE is a full path and start with /
    if [ ! -d $VAULT/$d/$TREE ] ; then
        warn "$d : No backup tree exist."
        continue
    fi
    curr_file="$VAULT/$d/$TREE$FILE"
    if [ ! -f $curr_file ] ; then
        warn "$d : Backup file $curr_file doesn't exist in tree"
        continue
    fi
    checksum=$(sha1sum $curr_file | cut -f 1 -d ' ')
    if [ "$curr_checksum" != "$checksum" ] ; then
        echo $checksum $curr_file
        curr_checksum="$checksum"
    fi
done
