#!/bin/bash

#BANK="/srv/backup"

function help {
    echo "Run connection test on all vaults in a bank."
    echo "dirvish_conntest need to in available in PATH"
}

function usage {
    echo "Usage: $0 /path/to/bank"
    echo "Where the path is excluding any trailing /-characters."
}

## -------------------------------------------------------------------------- ##
# Colors for prettier print
U='\033[0;0m'
R='\033[0;31m'
Y='\033[1;33m'
G='\033[0;32m'
B='\033[0;34m'
## -------------------------------------------------------------------------- ##
## Sanity checks
if [ $# -ne 1 ]; then
    echo -e "${R}Error:${U} Expected one vault bank as input." 1>&2
    usage 1>&2
    exit 8
else
    BANK="$1"
fi

## -------------------------------------------------------------------------- ##
## Doing the needful
echo "Connection test for bank $BANK"
for V in $(find $BANK -maxdepth 1 -type d | sort ) ; do
    printf "Vault %-10s: " $(basename $V)
    dirvish_conntest $V
done
