#!/bin/bash

help(){
	echo "Copy input file name to new file with file ending NAME.orig.sha256.SHA256SUM."
	echo "Where NAME is the input file name and SHA256SUM is the files sha256sum."
#	echo "Adding option -i as the first argument attempt to invert the process."
}

if [ $# -eq 1 ] ; then # Normal mode
	cp $1 $1.orig.sha256.$(sha256sum $1 | cut -f 1 -d ' ')
	if [ $? -ne 0 ]; then
		echo "Something went wrong during copy." 1>&2
		exit 1
	else
		echo "Copy made."
		exit 0
	fi
elif [ $# -eq 2 ] && [ $1 == '-i' ]; then # Invert mode
	echo "Inverting..."
	# Count found files
	result=$(ls -d $2* | grep -E '\.orig\.sha256\.[a-f0-9]{64}' | wc -l)
	if [ $result -ne 1 ]; then
		echo "Found $result sha'd files. Expected 1." 1>&2
		echo "Resolve this message by making sure there is only sha'd file." 1>&2
		echo "Exiting ..." 1>&2
		exit 1
	fi
	# else
	echo "Moving: " $(ls $2* | grep -E '\.orig\.sha256\.[a-f0-9]{64}')
	mv $(ls $2* | grep -E '\.orig\.sha256\.[a-f0-9]{64}') $2
	echo "Done!"
else
	help
	exit 1
fi
