#!/usr/bin/env python3
'''
List size of unlinked but not yet deleted files in bytes.

Recommended to run as root.
'''

import subprocess
import sys

CMD = "lsof | grep -i '(deleted)'" # Get all deleted files.


def sizeofdeletedfiles():
    '''
    Returns the size of deleted but not removed file or lsof return code if
    something went wrong.
    '''
    res = subprocess.run(CMD,capture_output=True,shell=True)
    if res.returncode:
        return res.returncode
    resrows = res.stdout.decode('utf-8').split("\n")
    fsize = (int(r.split()[-3]) for r in resrows if r)  # Negative index since
                                                        # not all row-column
                                                        # cells are populated in
                                                        # col 3 and 4
    return sum(fsize)


if __name__ == "__main__":
    res = sizeofdeletedfiles()
    if res < 256: # Assume something went wrong.
        sys.stderr.write(f"Warning: Result of {res} is less than 255. This is "\
                         f"likely an error returncode from lsof.")
        sys.exit(1)
    print(res)
